# to test a newly added hook, run on all files using:
# pre-commit run --all-files

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: check-yaml
      name: Attempt to load all yaml files to verify syntax

- repo: https://github.com/dbt-checkpoint/dbt-checkpoint
  rev: v1.0.0
  hooks:
  - id: check-source-has-loader
    files: ^models/
  - id: check-source-has-meta-keys
    files: ^models/
    args: ['--meta-keys', 'team', 'owner_name', '--']
  # 283 source tables without description as of 2023-01-06
  - id: check-source-table-has-description
    files: ^models/
    # please remove folders as documentation is added
    exclude: |
      (?x)(
        ^models/staging/asana/|
        ^models/staging/cloud_metadata/|
        ^models/staging/cloud_postgres/|
        ^models/staging/delighted/|
        ^models/staging/github/|
        ^models/staging/google_search_console/|
        ^models/staging/googlesheets/|
        ^models/staging/harvest/|
        ^models/staging/hubspot/|
        ^models/staging/intercom/|
        ^models/staging/jira/|
        ^models/staging/linkedin_organic/|
        ^models/staging/mailchimp/|
        ^models/staging/meetup/|
        ^models/staging/salesforce/|
        ^models/staging/slack/|
        ^models/staging/snowplow/|
        ^models/staging/thinkific/|
        ^models/staging/ticket_tailor/|
        ^models/staging/trello/|
        ^models/staging/twitter/|
        ^models/staging/youtube/|
        ^models/staging/zendesk/
      )
  # following is using the catalog
  # too long to run -- currently taking ~25min, which is not an acceptable wait time to commit 
  # - id: dbt-docs-generate
  # - id: check-model-name-contract
  #   args: [--pattern, "(dim_|fct_).*", "--"]
  #   files: models/marts/
  # 204 models without descriptions as of 2023-01-06
  # - id: check-model-has-properties-file
  #   name: Check that all models are listed in a YAML file
  # 297 models without descriptions as of 2023-01-06
  # - id: check-model-has-description
  #   name: Check that all models have a description