version: 2

models:
  - name: fct_asana_events
    description: "Events around a project's task in Asana (e.g. moved, changed status, comments, etc)"
    columns:
      - name: id
        tests:
          - unique
          - not_null

  - name: fct_asana_project_tasks
    description: "Every task in every Asana project. NOTE: a single task can belong to multiple projects"
    columns:
      - name: project_task_id
        description: "A surrogate key created via project_id and task_id"
        tests:
          - unique
          - not_null
      - name: project_id
        description: "System-generated unique ID of the project."
      - name: team_id
        description: "Foreign key referencing the team that the project is associated with"
      - name: owner_id
        description: "Foreign key referencing the user who owns the project."
      - name: task_id
        description: "System generated unique ID of the task."
      - name: parent_task_id
        description: "Self-referential id of the parent TASK that this is a subtask of."
      - name: workspace_id
        description: "Foreign key referencing the workspace that the project is associated with"
      - name: assignee_id
        description: "Foreign key referencing the user that is currently assigned the task."
      - name: completed_by_id
        description: "Foreign key referencing the user who completed the task. Note that this may be different than the assignee."
      - name: team_name
        description: "User-facing name of the project's team."
      - name: project_name
        description: "UI-facing name of the project."
      - name: project_owner_name
        description: "The name of the user who owns the project."
      - name: project_owner_email
        description: "The email of the user who owns the project."
      - name: is_template_project
        description: "Indicates whether or not a project is used as a template. Templated projects should excluded from analysis."
      - name: assignee_name
        description: "Name of the user that the task is currently assigned to."
      - name: current_status
        description: "The most recent progress status update for the project (free-form string)."
      - name: current_section_name
        description: "The name of the section that the task is currently in."
      - name: was_completed_on_time
        description: "Indicates if a task was completed on or before the due date."
      - name: task_name
        description: "User-facing name of the task."
      - name: task_notes
        description: "Free-form textual description associated with the task."
      - name: department
        description: "The department the task is associated with. Examples include: marketing, product, sales, etc."
      - name: est_hours
        description: "The estimated amount of time it will take to complete the task."
      - name: request_type
        description: "The type of request associated with a task. Examples include: task, bug, project, analysis, etc."
      - name: labels
        description: "ProServe only: Any labels associated with a task."
      - name: attachment_links
        description: "Links to any attachments within a task."
      - name: blocker
        description: "A free-form text field highlighting any blockers for the task."
      - name: priority
        description: >
          "A P1-4 scale indicating how urgent it is to complete the task:
          P1 - Need this done ASAP
          P2 - Need this done this week
          P3 - Need this done within the next few weeks
          P4 - This should be done eventually, but isn't high priority"
      - name: pull_request
        description: "A link to a pull request associated with the task."
      - name: board_name
        description: "ProServe only: The name of the board a task is on."
      - name: members
        description: "ProServe only: A list of employees assigned with the task."
      - name: engagement_type
        description: "ProServe only: indicates the type of engagement the task is a part of. Examples include Rapid Onboarding & Enterprise."
      - name: is_task_completed
        description: "Indicates whether or not a task has been marked as completed."
      - name: is_liked
        description: "Indicates whether or not a task has been liked."
      - name: is_deleted
        description: "Indicates whether or not a task has been deleted."
      - name: num_hearts
        description: "The number of hearts on a task."
      - name: num_likes
        description: "The number of likes on a task."
      - name: cost
        description: "ProServe only: The cost associated with a task."
      - name: proserve_card_url
        description: "ProServe only: A link to the card the task is associated with."
      - name: proserve_archived
        description: "ProServe only: Indicates whether or not a task has been archived."
      - name: proserve_sprint
        description: "ProServe only: The sprint number the task is associated with."
      - name: proserve_due_date_imported
        description: "ProServe only: The due date of the task."
      - name: proserve_start_date
        description: "ProServe only: The start date of the task."
      - name: proserve_last_activity_date
        description: "ProServe only: A timestamp indicating when the last activity associated with the task occured."
      - name: modified_at
        description: "Timestamp of when the task was last modified."
      - name: created_at
        description: "Timestamp of when the task was created."
      - name: start_on
        description: "The start date of the task, if a date range is given."
      - name: due_on
        description: "Date the task is due, if provided."
      - name: completed_at
        description: "Timestamp of when the task was marked complete."
      - name: task_type
        description: The type of task. These include default_task, milestone, and approval.

  - name: fct_jira_issue_field_values
    description: "This looks at the current custom fields on a given issue. For every custom field, we have it exist as its own column with the value associated."
    columns:
      - name: issue_id
        tests:
          - unique
          - not_null
      - name: cloud_environment
        description: "This is a single input field that indicates which cloud environment this issue pertains to (e.g. prod, test, staging)."
      - name: dbt_environment
        description: "This is a multiselect field that indicates what cloud environment issue pertains to (e.g. dbt-sandbox, dbt-prod, etc)."
      - name: environment_description
        description: "The description of the environment (e.g. DevSpace). In the Jira UI, this is located in the issue's description."

  - name: fct_jira_issue_status_events
    description: "This table contains all status/stage changes a Jira ticket/issue progreses through as well as how long the ticket was in a given stage for."
    columns:
      - name: id
        description: "The unique identifier. This is a hashed ID comprised of the issue_id, status_name, and the valid_starting_at timestamp."
        tests:
          - unique
          - not_null
      - name: status_name
        description: "The name of the status on the issue."
      - name: valid_starting_at
        description: "The timestamp when the issue first went into this status stage."
      - name: valid_ending_at
        description: "The timestamp when the issue moved onto the next status. If this is null then it means the ticket is currently in this stage or it is completed."
      - name: days_in_event
        description: "The total days the issue was in this stage."
      - name: is_first_status_event
        description: "Boolean to indicate if this is the first status event."
      - name: is_last_status_event
        description: "Boolean to indicate if this is the last status event."

  - name: fct_jira_issues
    description: "This contains all issues within Jira across the entire organization. Please note that epics are included as issues."
    columns:
      - name: issue_id
        tests:
          - unique
          - not_null
      - name: assignee_user_id
        description: '{{ doc("jira_issue_assignee_user_id") }}'
      - name: created_at
        description: '{{ doc("jira_issue_created_at") }}'
      - name: creator_user_id
        description: '{{ doc("jira_issue_creator_user_id") }}'
      - name: issue_description
        description: '{{ doc("jira_issue_issue_description") }}'
      - name: due_date
        description: '{{ doc("jira_issue_due_date") }}'
      - name: environment
        description: '{{ doc("jira_issue_environment") }}'
      - name: issue_type_id
        description: '{{ doc("jira_issue_issue_type_id") }}'
      - name: issue_key
        description: '{{ doc("jira_issue_issue_key") }}'
      - name: original_estimate_seconds
        description: '{{ doc("jira_issue_original_estimate_seconds") }}'
      - name: parent_issue_id
        description: '{{ doc("jira_issue_parent_issue_id") }}'
      - name: priority_id
        description: '{{ doc("jira_issue_priority_id") }}'
      - name: project_id
        description: '{{ doc("jira_issue_project_id") }}'
      - name: remaining_estimate_seconds
        description: '{{ doc("jira_issue_remaining_estimate_seconds") }}'
      - name: reporter_user_id
        description: '{{ doc("jira_issue_reporter_user_id") }}'
      - name: resolution_id
        description: '{{ doc("jira_issue_resolution_id") }}'
      - name: resolved_at
        description: '{{ doc("jira_issue_resolved_at") }}'
      - name: status_id
        description: '{{ doc("jira_issue_status_id") }}'
      - name: status_changed_at
        description: '{{ doc("jira_issue_status_changed_at") }}'
      - name: issue_name
        description: '{{ doc("jira_issue_issue_name") }}'
      - name: time_spent_seconds
        description: '{{ doc("jira_issue_time_spent_seconds") }}'
      - name: updated_at
        description: '{{ doc("jira_issue_updated_at") }}'
      - name: work_ratio
        description: '{{ doc("jira_issue_work_ratio") }}'
      - name: issue_labels
        description: The current labels on the Jira ticket.
      - name: severity_security_start_at
        description: The first timestamp where the ticket was marked as being security related.
      - name: is_security_prioritized
        description: A boolean that indicaites, if the issue is security prioritized, then flag whether the ticket has been prioritized since it was marked as security-critical.