name: Auto-create Hightouch Exposures Pull Request
on:
  push:
    branches:
      - hightouch-exposures
      
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR exists
        id: check
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          prs=$(gh pr list \
              --repo "$GITHUB_REPOSITORY" \
              --json baseRefName,headRefName \
              --jq '
                  map(select(.baseRefName == "main" and .headRefName == "hightouch-exposures"))
                  | length
              ')
          if ((prs > 0)); then
              echo "skip=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Create Pull Request
        if: '!steps.check.outputs.skip'
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'AUTOMATED: Update Hightouch sync exposures',
              owner,
              repo,
              head: '${{ github.ref_name }}',
              base: 'main',
              body: [
                'This is an automated PR to update the Hightouch Sync Exposures file.',
                '',
                'Please do not delete the branch after merging.'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['automated pr']
            });
